apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-ms 
spec:
 replicas: 3
 selector:
   matchLabels:
    app: order-ms
 template:
  metadata:
   labels:
    app: order-ms
  spec:  
   containers:
    - name: order-ms-liveness
      image: pseshagiri/microservices:order-ms-2.0
      imagePullPolicy: Always
      ports:
       - containerPort: 9001
      livenessProbe:
       httpGet:
        path: /orders
        port: 9001
        httpHeaders:
         - name: Custom-Header
           value: Awesome
       initialDelaySeconds: 3
       periodSeconds: 3         

# service type loadbalance
---

apiVersion: v1
kind: Service
metadata:
 name: order-ms
 labels:
  app: order-ms
  k8s: order-ms
spec:
 selector:
  app: order-ms
 ports:
  - name: http
    port: 9001
    protocol: TCP
    targetPort: 9001 
 type: LoadBalancer
   
 
       
   