apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-ms 
spec:
 replicas: 2
 selector:
   matchLabels:
    app: order-ms
 template:
  metadata:
   labels:
    app: order-ms
  spec:  
   containers:
    - name: order-ms
      image: pseshagiri/microservices:order-ms-1.0
      imagePullPolicy: Always
      ports:
       - containerPort: 9001         

# service type loadbalance
---

apiVersion: app/v1
kind: Service
metadata:
 name: order-ms
 labels:
  app: order-ms
  k8s: order-ms
spec:
 selector:
  app: order-ms
 ports:
  - name: http
    port: 9001
    protocol: tcp
    targetPort: 9001 
 type: LoadBalancer
   
 
       
   